name: CI / Build and test
on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Set up config files
              run: cp config/config.example.toml config/config.toml

            - name: Cypress install
              uses: cypress-io/github-action@v6
              with:
                  # Disable running of tests within install job
                  runTests: false
                  build: pnpm run build
              continue-on-error: true

            - name: Save build folder
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  if-no-files-found: error
                  path: dist

    cypress-run:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Set up config files
              run: cp config/config.example.toml config/config.toml

            - name: Download the build folder
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.10.0

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: pnpm start
                  browser: chrome

            - name: Upload screenshots
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots

    deploy:
        runs-on: ubuntu-latest
        needs: cypress-run
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download the build folder
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}
            - name: Upload to server
              run: |
                  # Remove unnecessary files
                  rm -rf .git
                  rm -rf .github
                  rm -rf config
                  rsync -e "ssh -o StrictHostKeyChecking=no" -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
            - name: Trigger redeploy
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_PATH }} && ./ci.sh 2>&1 /dev/null"
